/**
 * Design Token Mapping — Converts Figma tokens to Tailwind CSS variables
 * and generates the token configuration files.
 */

import type { DesignToken } from "../engine/registry.js";

export interface TokenExport {
  css: string;
  tailwindExtend: Record<string, Record<string, string>>;
  json: Record<string, unknown>;
}

/**
 * Export tokens to CSS custom properties, Tailwind config, and JSON.
 */
export function exportTokens(tokens: DesignToken[], mode = "default"): TokenExport {
  const cssLines: string[] = [":root {"];
  const tailwindExtend: Record<string, Record<string, string>> = {
    colors: {},
    spacing: {},
    borderRadius: {},
    fontSize: {},
    boxShadow: {},
  };
  const json: Record<string, unknown> = {};

  for (const token of tokens) {
    const value = resolveTokenValue(token, mode);
    if (value === null) continue;

    const cssVar = token.cssVariable;
    cssLines.push(`  ${cssVar}: ${value};`);
    json[token.name] = value;

    // Map to Tailwind categories
    const tailwindKey = tokenToTailwindKey(token.name);
    switch (token.type) {
      case "color":
        tailwindExtend.colors[tailwindKey] = `var(${cssVar})`;
        break;
      case "spacing":
        tailwindExtend.spacing[tailwindKey] = `var(${cssVar})`;
        break;
      case "radius":
        tailwindExtend.borderRadius[tailwindKey] = `var(${cssVar})`;
        break;
      case "typography":
        tailwindExtend.fontSize[tailwindKey] = `var(${cssVar})`;
        break;
      case "shadow":
        tailwindExtend.boxShadow[tailwindKey] = `var(${cssVar})`;
        break;
    }
  }

  cssLines.push("}");

  // Generate dark mode overrides if tokens have a dark mode
  const hasDarkMode = tokens.some((t) =>
    Object.keys(t.values).some((k) => k.toLowerCase().includes("dark"))
  );

  if (hasDarkMode) {
    cssLines.push("");
    cssLines.push(".dark {");
    for (const token of tokens) {
      const darkValue = resolveTokenValue(token, "dark");
      if (darkValue !== null) {
        cssLines.push(`  ${token.cssVariable}: ${darkValue};`);
      }
    }
    cssLines.push("}");
  }

  return {
    css: cssLines.join("\n"),
    tailwindExtend: cleanEmpty(tailwindExtend),
    json,
  };
}

/**
 * Generate a Tailwind config extend block from tokens.
 */
export function generateTailwindExtend(tokens: DesignToken[]): string {
  const { tailwindExtend } = exportTokens(tokens);

  const lines: string[] = [
    "// Auto-generated by Noche — do not edit manually",
    "// Re-run `noche tokens` to regenerate from Figma",
    "",
    "export const arkTokens = {",
  ];

  for (const [category, values] of Object.entries(tailwindExtend)) {
    if (Object.keys(values).length === 0) continue;
    lines.push(`  ${category}: {`);
    for (const [key, val] of Object.entries(values)) {
      lines.push(`    "${key}": "${val}",`);
    }
    lines.push("  },");
  }

  lines.push("};");
  return lines.join("\n");
}

// ── Helpers ──────────────────────────────────────────────────

function resolveTokenValue(token: DesignToken, mode: string): string | null {
  // Try exact mode match
  if (token.values[mode] !== undefined) {
    return formatCssValue(token.values[mode], token.type);
  }

  // Try case-insensitive match
  const modeKey = Object.keys(token.values).find(
    (k) => k.toLowerCase() === mode.toLowerCase()
  );
  if (modeKey) {
    return formatCssValue(token.values[modeKey], token.type);
  }

  // Fall back to first available mode
  const firstKey = Object.keys(token.values)[0];
  if (firstKey) {
    return formatCssValue(token.values[firstKey], token.type);
  }

  return null;
}

function formatCssValue(value: string | number, type: string): string {
  if (typeof value === "number") {
    switch (type) {
      case "spacing":
      case "radius":
        return `${value}px`;
      case "typography":
        return `${value}px`;
      default:
        return String(value);
    }
  }
  return String(value);
}

function tokenToTailwindKey(name: string): string {
  return name
    .replace(/[\s/]+/g, "-")
    .replace(/([a-z])([A-Z])/g, "$1-$2")
    .toLowerCase()
    .replace(/^-+|-+$/g, "");
}

function cleanEmpty(obj: Record<string, Record<string, string>>): Record<string, Record<string, string>> {
  const result: Record<string, Record<string, string>> = {};
  for (const [key, val] of Object.entries(obj)) {
    if (Object.keys(val).length > 0) {
      result[key] = val;
    }
  }
  return result;
}
