/**
 * Auto-PR — turn a detected design system change into a pull request.
 *
 * Flow on detected change:
 *   1. Run `git checkout -b memoire/sync-<timestamp>` in the project
 *   2. Stage all generated file changes
 *   3. Commit with a diff summary
 *   4. Push the branch
 *   5. Open a PR via `gh pr create` (falls back to printing the URL)
 *
 * Requires: `git` CLI + `gh` CLI authenticated. Silently skips if `gh` is
 * unavailable — in that case, the branch is still pushed and the URL is
 * printed for manual PR creation.
 */

import { spawnSync, type SpawnSyncReturns } from "node:child_process";
import type { DiffPayload } from "../commands/diff.js";

export interface AutoPrResult {
  status: "opened" | "pushed-no-gh" | "skipped-no-changes" | "failed";
  branch?: string;
  prUrl?: string;
  commitSha?: string;
  error?: string;
}

export interface AutoPrOptions {
  cwd: string;
  diff: DiffPayload;
  /** Base branch to target (default: main) */
  base?: string;
  /** Dry-run: print what would happen without executing git */
  dryRun?: boolean;
}

function run(cmd: string, args: string[], cwd: string): SpawnSyncReturns<string> {
  return spawnSync(cmd, args, { cwd, encoding: "utf-8" });
}

function hasTool(cmd: string): boolean {
  const r = spawnSync(cmd, ["--version"], { encoding: "utf-8" });
  return r.status === 0;
}

/**
 * Open an auto-PR for a design system diff. Safe to call when there
 * are no changes — returns `skipped-no-changes`.
 */
export async function openAutoPR(opts: AutoPrOptions): Promise<AutoPrResult> {
  const { cwd, diff, base = "main", dryRun } = opts;

  const totalChanges =
    diff.tokens.added.length +
    diff.tokens.removed.length +
    diff.tokens.changed.length +
    diff.components.added.length +
    diff.components.removed.length;

  if (totalChanges === 0) return { status: "skipped-no-changes" };
  if (!hasTool("git")) return { status: "failed", error: "git not found" };

  const timestamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
  const branch = `memoire/sync-${timestamp}`;
  const title = buildTitle(diff);
  const body = buildBody(diff);

  if (dryRun) {
    return { status: "opened", branch, prUrl: `(dry-run) would open: ${title}` };
  }

  // 1. Check if there's anything to commit at all
  const statusRes = run("git", ["status", "--porcelain"], cwd);
  if (statusRes.status !== 0) return { status: "failed", error: `git status failed: ${statusRes.stderr}` };
  if (!statusRes.stdout.trim()) return { status: "skipped-no-changes" };

  // 2. Create branch
  const checkout = run("git", ["checkout", "-b", branch], cwd);
  if (checkout.status !== 0) return { status: "failed", error: `branch create failed: ${checkout.stderr}` };

  // 3. Stage changes
  const add = run("git", ["add", "-A"], cwd);
  if (add.status !== 0) return { status: "failed", error: `git add failed: ${add.stderr}` };

  // 4. Commit
  const commitMsg = `${title}\n\n${body}`;
  const commit = run("git", ["commit", "-m", commitMsg], cwd);
  if (commit.status !== 0) return { status: "failed", error: `git commit failed: ${commit.stderr}` };

  // 5. Grab commit SHA
  const rev = run("git", ["rev-parse", "HEAD"], cwd);
  const commitSha = rev.stdout.trim().slice(0, 7);

  // 6. Push
  const push = run("git", ["push", "-u", "origin", branch], cwd);
  if (push.status !== 0) return { status: "failed", error: `git push failed: ${push.stderr}` };

  // 7. Open PR via gh CLI if available
  if (hasTool("gh")) {
    const pr = run("gh", ["pr", "create", "--base", base, "--head", branch, "--title", title, "--body", body], cwd);
    if (pr.status === 0) {
      const url = pr.stdout.trim().split("\n").pop() ?? "";
      return { status: "opened", branch, commitSha, prUrl: url };
    }
  }

  return { status: "pushed-no-gh", branch, commitSha };
}

function buildTitle(diff: DiffPayload): string {
  const parts: string[] = [];
  if (diff.tokens.added.length) parts.push(`+${diff.tokens.added.length} tokens`);
  if (diff.tokens.changed.length) parts.push(`~${diff.tokens.changed.length} tokens`);
  if (diff.tokens.removed.length) parts.push(`-${diff.tokens.removed.length} tokens`);
  if (diff.components.added.length) parts.push(`+${diff.components.added.length} components`);
  if (diff.components.removed.length) parts.push(`-${diff.components.removed.length} components`);
  return `chore(memoire): sync design system (${parts.join(", ")})`;
}

function buildBody(diff: DiffPayload): string {
  const lines: string[] = ["Generated by `memi sync --auto-pr`.", ""];

  if (diff.tokens.added.length > 0) {
    lines.push("## Tokens added", "");
    for (const t of diff.tokens.added) lines.push(`- \`${t}\``);
    lines.push("");
  }
  if (diff.tokens.changed.length > 0) {
    lines.push("## Tokens changed", "");
    for (const c of diff.tokens.changed) lines.push(`- \`${c.name}\`: \`${c.from}\` → \`${c.to}\``);
    lines.push("");
  }
  if (diff.tokens.removed.length > 0) {
    lines.push("## Tokens removed", "");
    for (const t of diff.tokens.removed) lines.push(`- \`${t}\``);
    lines.push("");
  }
  if (diff.components.added.length > 0) {
    lines.push("## Components added", "");
    for (const c of diff.components.added) lines.push(`- ${c}`);
    lines.push("");
  }
  if (diff.components.removed.length > 0) {
    lines.push("## Components removed", "");
    for (const c of diff.components.removed) lines.push(`- ${c}`);
    lines.push("");
  }

  lines.push("---");
  if (diff.previousSync) lines.push(`Previous sync: \`${diff.previousSync}\``);
  if (diff.lastSync) lines.push(`Current sync:  \`${diff.lastSync}\``);
  return lines.join("\n");
}
