import { afterEach, describe, expect, it, vi } from "vitest";
import { Command } from "commander";
import { registerPullCommand } from "../pull.js";
import { captureLogs } from "./test-helpers.js";

afterEach(() => {
  vi.restoreAllMocks();
  process.exitCode = 0;
});

describe("pull --json", () => {
  it("emits structured payload on successful pull", async () => {
    const logs = captureLogs();
    const engine = makePullEngine({ figmaConnected: true });
    const program = new Command();

    registerPullCommand(program, engine as never);
    await program.parseAsync(["pull", "--json"], { from: "user" });

    const payload = JSON.parse(logs.at(-1)!);

    expect(payload.status).toBe("completed");
    expect(payload.figma.connected).toBe(true);
    expect(payload.designSystem.tokens).toBe(3);
    expect(payload.designSystem.components).toBe(2);
    expect(payload.specs.autoGenerated).toBe(1);
    expect(payload.specs.total).toBe(3);
    expect(typeof payload.elapsedMs).toBe("number");
    expect(payload.error).toBeUndefined();
  });

  it("emits failed payload when figma not connected", async () => {
    const logs = captureLogs();
    const engine = makePullEngine({ figmaConnected: false });
    const program = new Command();

    registerPullCommand(program, engine as never);
    await program.parseAsync(["pull", "--json"], { from: "user" });

    const payload = JSON.parse(logs.at(-1)!);

    expect(payload.status).toBe("failed");
    expect(payload.figma.connected).toBe(false);
    expect(payload.error).toBeDefined();
    expect(process.exitCode).toBe(1);
  });

  it("suppresses text output in json mode", async () => {
    const logs = captureLogs();
    const engine = makePullEngine({ figmaConnected: true });
    const program = new Command();

    registerPullCommand(program, engine as never);
    await program.parseAsync(["pull", "--json"], { from: "user" });

    expect(logs).toHaveLength(1);
    expect(() => JSON.parse(logs[0])).not.toThrow();
  });
});

function makePullEngine({ figmaConnected }: { figmaConnected: boolean }) {
  const ds = {
    tokens: [{ name: "a" }, { name: "b" }, { name: "c" }],
    components: [{ name: "Button" }, { name: "Card" }],
    styles: [{ name: "fill/primary" }],
    lastSync: "2026-03-28T00:00:00.000Z",
  };

  return {
    async init() {},
    async ensureFigmaConnected() {
      if (!figmaConnected) throw new Error("No Figma plugin connected");
    },
    async pullDesignSystem() {},
    registry: {
      designSystem: ds,
      async getAllSpecs() {
        return [
          { type: "component", name: "Button", tags: ["auto-generated"] },
          { type: "component", name: "Card", tags: [] },
          { type: "page", name: "Dashboard" },
        ];
      },
    },
  };
}
