import type { Command } from "commander";
import type { MemoireEngine } from "../engine/core.js";
import { checkCapabilities, formatCapabilityError } from "../engine/capabilities.js";
import { diffDesignSystem } from "../engine/token-differ.js";
import { ui } from "../tui/format.js";
import { auditTokensForWcag, type WcagTokenReport } from "../figma/wcag-token-checker.js";

export interface PullPayload {
  status: "completed" | "failed";
  figma: {
    connected: boolean;
  };
  designSystem: {
    tokens: number;
    components: number;
    styles: number;
  };
  specs: {
    autoGenerated: number;
    total: number;
  };
  elapsedMs: number;
  error?: string;
  wcagReport?: WcagTokenReport;
}

export function registerPullCommand(program: Command, engine: MemoireEngine) {
  program
    .command("pull")
    .description("Pull design system from connected Figma file")
    .option("--rest", "Pull via Figma REST API (no plugin required — needs FIGMA_TOKEN + FIGMA_FILE_KEY)")
    .option("--force", "Bypass the 5-minute pull cache and force a fresh pull")
    .option("--json", "Output pull results as JSON")
    .option("--wcag", "Run WCAG token audit after pull. Sets exit code 2 when failures are found.")
    .action(async (opts: { rest?: boolean; force?: boolean; json?: boolean; wcag?: boolean }) => {
      const start = Date.now();
      await engine.init();

      // REST mode — bypass plugin entirely
      if (opts.rest) {
        if (!opts.json) console.log(`\n  Pulling via REST API${opts.force ? " (forced)" : ""}...\n`);

        try {
          const before = engine.snapshotDesignSystem?.() ?? { tokens: [], components: [], styles: [], lastSync: "" };
          await engine.pullDesignSystemREST(opts.force ?? false);
          const ds = engine.registry.designSystem;
          const specs = await engine.registry.getAllSpecs();
          const autoSpecs = specs.filter((s) => s.type === "component" && s.tags?.includes("auto-generated"));

          const payload: PullPayload = {
            status: "completed",
            figma: { connected: false },
            designSystem: { tokens: ds.tokens.length, components: ds.components.length, styles: ds.styles.length },
            specs: { autoGenerated: autoSpecs.length, total: specs.length },
            elapsedMs: Date.now() - start,
          };

          // WCAG audit — REST path
          if (opts.wcag) {
            const wcagReport = auditTokensForWcag(ds.tokens);
            payload.wcagReport = wcagReport;
            if (wcagReport.hasFailures) process.exitCode = 2;
          }

          if (opts.json) {
            const after = engine.snapshotDesignSystem?.() ?? ds;
            const diff = diffDesignSystem(before, after);
            (payload as unknown as Record<string, unknown>).diff = {
              hasChanges: diff.hasChanges,
              summary: diff.summary,
              tokens: diff.tokens.length,
              components: diff.components.length,
              styles: diff.styles.length,
            };
            console.log(JSON.stringify(payload, null, 2));
            return;
          }

          console.log(`  Done. ${ds.tokens.length} tokens, ${ds.components.length} components, ${ds.styles.length} styles`);
          console.log(`  Design system saved to .memoire/design-system.json`);
          if (autoSpecs.length > 0) {
            console.log(`  Auto-generated ${autoSpecs.length} component specs — run \`memi generate\` to create code`);
          }

          if (opts.wcag && payload.wcagReport) {
            printWcagReport(payload.wcagReport);
          }

          console.log("");
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          if (opts.json) {
            const payload: PullPayload = {
              status: "failed",
              figma: { connected: false },
              designSystem: { tokens: 0, components: 0, styles: 0 },
              specs: { autoGenerated: 0, total: 0 },
              elapsedMs: Date.now() - start,
              error: msg,
            };
            console.log(JSON.stringify(payload, null, 2));
          } else {
            console.error(`\n  Error: ${msg}\n`);
          }
          process.exitCode = 1;
        }
        return;
      }

      // Check capabilities before attempting connection
      const caps = checkCapabilities("pull", {
        figma: engine.figma?.isConnected ?? false,
        ai: !!process.env.ANTHROPIC_API_KEY,
        specs: false,
        generatedCode: false,
        research: false,
        daemon: false,
      });

      if (!caps.ok && !engine.figma?.isConnected) {
        // Try to connect first
        try {
          await engine.ensureFigmaConnected();
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          if (opts.json) {
            const payload: PullPayload = {
              status: "failed",
              figma: { connected: false },
              designSystem: { tokens: 0, components: 0, styles: 0 },
              specs: { autoGenerated: 0, total: 0 },
              elapsedMs: Date.now() - start,
              error: msg,
            };
            console.log(JSON.stringify(payload, null, 2));
            process.exitCode = 1;
            return;
          }
          console.error(formatCapabilityError(caps, "pull"));
          process.exitCode = 1;
          return;
        }
      }

      // Snapshot before pull for diff
      const before = engine.snapshotDesignSystem?.() ?? { tokens: [], components: [], styles: [], lastSync: "" };

      if (!opts.json) console.log(`\n  Pulling design system${opts.force ? " (forced)" : ""}...\n`);
      await engine.pullDesignSystem(opts.force ?? false);

      const specs = await engine.registry.getAllSpecs();
      const autoSpecs = specs.filter((s) => s.type === "component" && s.tags?.includes("auto-generated"));
      const ds = engine.registry.designSystem;

      const payload: PullPayload = {
        status: "completed",
        figma: { connected: true },
        designSystem: {
          tokens: ds.tokens.length,
          components: ds.components.length,
          styles: ds.styles.length,
        },
        specs: {
          autoGenerated: autoSpecs.length,
          total: specs.length,
        },
        elapsedMs: Date.now() - start,
      };

      // Compute diff
      const after = engine.snapshotDesignSystem?.() ?? engine.registry.designSystem;
      const diff = diffDesignSystem(before, after);

      // WCAG audit — plugin path
      if (opts.wcag) {
        const wcagReport = auditTokensForWcag(ds.tokens);
        payload.wcagReport = wcagReport;
        if (wcagReport.hasFailures) process.exitCode = 2;
      }

      if (opts.json) {
        (payload as unknown as Record<string, unknown>).diff = {
          hasChanges: diff.hasChanges,
          summary: diff.summary,
          tokens: diff.tokens.length,
          components: diff.components.length,
          styles: diff.styles.length,
        };
        console.log(JSON.stringify(payload, null, 2));
        return;
      }

      console.log(`\n  Done. Design system saved to .memoire/design-system.json`);

      // Show diff
      if (diff.hasChanges) {
        console.log();
        if (diff.tokens.length > 0) {
          console.log("  TOKENS");
          for (const c of diff.tokens.slice(0, 20)) {
            const icon = c.type === "added" ? ui.green("+") : c.type === "removed" ? ui.red("-") : ui.dim("~");
            console.log(`    ${icon} ${c.name}  ${ui.dim(c.type)}`);
          }
          if (diff.tokens.length > 20) console.log(`    ${ui.dim(`... and ${diff.tokens.length - 20} more`)}`);
        }
        if (diff.components.length > 0) {
          console.log("  COMPONENTS");
          for (const c of diff.components.slice(0, 10)) {
            const icon = c.type === "added" ? ui.green("+") : c.type === "removed" ? ui.red("-") : ui.dim("~");
            console.log(`    ${icon} ${c.name}  ${ui.dim(c.type)}`);
          }
        }
        if (diff.styles.length > 0) {
          console.log("  STYLES");
          for (const c of diff.styles.slice(0, 10)) {
            const icon = c.type === "added" ? ui.green("+") : c.type === "removed" ? ui.red("-") : ui.dim("~");
            console.log(`    ${icon} ${c.name}  ${ui.dim(c.type)}`);
          }
        }
        console.log();
        console.log(`  ${diff.summary}`);
      } else {
        console.log("  No changes detected.");
      }

      if (autoSpecs.length > 0) {
        console.log(`  Auto-generated ${autoSpecs.length} component specs — run \`memi generate\` to create code`);
      }

      if (opts.wcag && payload.wcagReport) {
        printWcagReport(payload.wcagReport);
      }

      console.log("");
    });
}

/**
 * Print a human-readable WCAG token audit summary to stdout.
 * Failures are printed individually with token name, value, and ratio.
 */
function printWcagReport(report: WcagTokenReport): void {
  const { summary, results } = report;
  console.log();
  console.log(`  wcag audit  ${summary.total} tokens checked`);
  console.log(`  [pass]  ${String(summary.pass).padStart(2)}  no issues`);
  if (summary.warn > 0) {
    console.log(`  [warn]  ${String(summary.warn).padStart(2)}  low contrast (AA-large only)`);
  }
  if (summary.fail > 0) {
    console.log(`  [fail]  ${String(summary.fail).padStart(2)}  inaccessible`);
    console.log();
    for (const r of results.filter((r) => r.status === "fail")) {
      console.log(`    FAIL  ${r.tokenName}  ${r.issue ?? ""}  [${r.wcagCriterion ?? ""}]`);
    }
  }
}
