/**
 * shadcn Mapper — Maps component specs to shadcn/ui primitives
 * and generates production-ready React + TypeScript components.
 */

import type { ComponentSpec } from "../specs/types.js";
import type { CodegenContext } from "./generator.js";
import type { DesignToken } from "../engine/registry.js";

interface ComponentCode {
  component: string;
  barrel: string;
}

const SHADCN_IMPORTS: Record<string, string> = {
  Card: `import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"`,
  Button: `import { Button } from "@/components/ui/button"`,
  Badge: `import { Badge } from "@/components/ui/badge"`,
  Input: `import { Input } from "@/components/ui/input"`,
  Label: `import { Label } from "@/components/ui/label"`,
  Table: `import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"`,
  Tabs: `import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"`,
  Dialog: `import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"`,
  Select: `import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"`,
  Avatar: `import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"`,
  Separator: `import { Separator } from "@/components/ui/separator"`,
  Skeleton: `import { Skeleton } from "@/components/ui/skeleton"`,
  Tooltip: `import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip"`,
  DropdownMenu: `import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"`,
  Sheet: `import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet"`,
  ScrollArea: `import { ScrollArea } from "@/components/ui/scroll-area"`,
  Switch: `import { Switch } from "@/components/ui/switch"`,
  Checkbox: `import { Checkbox } from "@/components/ui/checkbox"`,
  Textarea: `import { Textarea } from "@/components/ui/textarea"`,
  Progress: `import { Progress } from "@/components/ui/progress"`,
  Sidebar: `import { SidebarProvider, Sidebar, SidebarContent, SidebarHeader, SidebarFooter } from "@/components/ui/sidebar"`,
  Slider: `import { Slider } from "@/components/ui/slider"`,
  RadioGroup: `import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group"`,
  Popover: `import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover"`,
  Accordion: `import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion"`,
  Alert: `import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"`,
  Calendar: `import { Calendar } from "@/components/ui/calendar"`,
  Carousel: `import { Carousel, CarouselContent, CarouselItem, CarouselNext, CarouselPrevious } from "@/components/ui/carousel"`,
  Command: `import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from "@/components/ui/command"`,
  Toggle: `import { Toggle } from "@/components/ui/toggle"`,
  ToggleGroup: `import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group"`,
  NavigationMenu: `import { NavigationMenu, NavigationMenuContent, NavigationMenuItem, NavigationMenuLink, NavigationMenuList, NavigationMenuTrigger } from "@/components/ui/navigation-menu"`,
  Breadcrumb: `import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from "@/components/ui/breadcrumb"`,
  Pagination: `import { Pagination, PaginationContent, PaginationItem, PaginationLink, PaginationNext, PaginationPrevious } from "@/components/ui/pagination"`,
};

export function generateComponent(spec: ComponentSpec, ctx: CodegenContext): ComponentCode {
  const imports = buildImports(spec);
  const propsInterface = buildPropsInterface(spec);
  const tokens = ctx.designSystem?.tokens ?? [];
  const componentBody = buildComponentBody(spec, tokens);
  const variantTypes = buildVariantType(spec);

  // Build destructured props, handling empty props case
  const propNames = Object.keys(spec.props);
  const destructuredProps: string[] = [...propNames];
  if (spec.variants.length > 1) {
    destructuredProps.push(`variant = "default"`);
  }
  destructuredProps.push("className");
  destructuredProps.push("...props");

  const propsStr = destructuredProps.join(", ");

  const component = [
    `// Generated by Memoire · memi generate ${spec.name} · https://memoire.cv`,
    `"use client"`,
    "",
    ...imports,
    "",
    `import { cn } from "@/lib/utils"`,
    "",
    variantTypes,
    propsInterface,
    "",
    `export function ${spec.name}({ ${propsStr} }: ${spec.name}Props) {`,
    componentBody,
    "}",
    "",
  ].filter(Boolean).join("\n");

  const barrel = [
    `export { ${spec.name} } from "./${spec.name}"`,
    `export type { ${spec.name}Props } from "./${spec.name}"`,
    "",
  ].join("\n");

  return { component, barrel };
}

function buildImports(spec: ComponentSpec): string[] {
  const imports: string[] = [`import * as React from "react"`];

  for (const base of spec.shadcnBase) {
    const imp = SHADCN_IMPORTS[base];
    if (imp) imports.push(imp);
  }

  return imports;
}

function buildPropsInterface(spec: ComponentSpec): string {
  const lines: string[] = [`export interface ${spec.name}Props extends React.HTMLAttributes<HTMLDivElement> {`];

  for (const [name, type] of Object.entries(spec.props)) {
    const tsType = mapPropType(type);
    const optional = type.endsWith("?") ? "?" : "";
    lines.push(`  ${name}${optional}: ${tsType}`);
  }

  if (spec.variants.length > 1) {
    lines.push(`  variant?: ${spec.name}Variant`);
  }

  lines.push("}");
  return lines.join("\n");
}

function buildVariantType(spec: ComponentSpec): string {
  if (spec.variants.length <= 1) return "";

  const variants = spec.variants.map((v) => `"${v}"`).join(" | ");
  return `export type ${spec.name}Variant = ${variants}\n`;
}

function buildComponentBody(spec: ComponentSpec, tokens: DesignToken[] = []): string {
  const hasCard = spec.shadcnBase.includes("Card");
  const hasBadge = spec.shadcnBase.includes("Badge");
  const hasButton = spec.shadcnBase.includes("Button");
  const hasInput = spec.shadcnBase.includes("Input");
  const hasAvatar = spec.shadcnBase.includes("Avatar");
  const hasDialog = spec.shadcnBase.includes("Dialog");
  const tokenStyles = buildTokenStyles(spec, tokens);
  const variantLogic = buildVariantLogic(spec);

  if (hasCard) {
    return buildCardComponent(spec, hasBadge, tokenStyles, variantLogic);
  }

  if (hasButton) {
    return buildButtonComponent(spec, tokenStyles, variantLogic);
  }

  if (hasInput) {
    return buildInputComponent(spec, tokenStyles);
  }

  if (hasAvatar) {
    return buildAvatarComponent(spec, tokenStyles);
  }

  if (hasDialog) {
    return buildDialogComponent(spec, tokenStyles);
  }

  // Default: smart div wrapper with variant support
  const lines: string[] = [];
  if (variantLogic) lines.push(variantLogic, "");
  lines.push("  return (");
  const styleAttr = tokenStyles ? ` style={${tokenStyles}}` : "";
  const variantClass = spec.variants.length > 1 ? ", variantClasses" : "";
  lines.push(`    <div className={cn("${defaultClasses(spec)}"${variantClass}, className)}${styleAttr} {...props}>`);

  for (const [name, type] of Object.entries(spec.props)) {
    if (type === "boolean" || type === "boolean?") {
      lines.push(`      {${name} && <div className="text-sm">{${name}}</div>}`);
    } else if (type === "ReactNode" || type === "ReactNode?") {
      lines.push(`      {${name}}`);
    } else {
      lines.push(`      {${name} && <span className="text-sm">{${name}}</span>}`);
    }
  }

  lines.push("    </div>");
  lines.push("  )");
  return lines.join("\n");
}

/** Generate variant CSS class mapping logic. */
function buildVariantLogic(spec: ComponentSpec): string | null {
  if (spec.variants.length <= 1) return null;

  const variantMap: string[] = [];
  for (const v of spec.variants) {
    const classes = inferVariantClasses(v, spec);
    variantMap.push(`    "${v}": "${classes}",`);
  }

  return [
    `  const variantStyles: Record<${spec.name}Variant, string> = {`,
    ...variantMap,
    `  }`,
    `  const variantClasses = variantStyles[variant ?? "default"] ?? ""`,
  ].join("\n");
}

/** Infer Tailwind classes for a variant name. */
function inferVariantClasses(variant: string, spec: ComponentSpec): string {
  const v = variant.toLowerCase();

  // Common variant → Tailwind class mappings
  const map: Record<string, string> = {
    default: "",
    primary: "bg-primary text-primary-foreground",
    secondary: "bg-secondary text-secondary-foreground",
    destructive: "bg-destructive text-destructive-foreground",
    outline: "border border-input bg-background hover:bg-accent hover:text-accent-foreground",
    ghost: "hover:bg-accent hover:text-accent-foreground",
    link: "text-primary underline-offset-4 hover:underline",
    compact: "p-2 text-sm",
    large: "p-6 text-lg",
    small: "p-1 text-xs",
    success: "bg-green-500/10 text-green-700 border-green-200",
    warning: "bg-yellow-500/10 text-yellow-700 border-yellow-200",
    error: "bg-red-500/10 text-red-700 border-red-200",
    info: "bg-blue-500/10 text-blue-700 border-blue-200",
    online: "bg-green-500",
    offline: "bg-gray-400",
    away: "bg-yellow-500",
    active: "bg-primary/10 font-medium",
    inactive: "opacity-60",
    disabled: "opacity-50 pointer-events-none",
    loading: "animate-pulse",
  };

  return map[v] ?? "";
}

function buildButtonComponent(spec: ComponentSpec, tokenStyles?: string, variantLogic?: string | null): string {
  const props = Object.keys(spec.props);
  const labelProp = props.find((p) => /label|text|children/i.test(p)) ?? props[0];
  const iconProp = props.find((p) => /icon/i.test(p));
  const disabledProp = props.find((p) => /disabled/i.test(p));

  const lines: string[] = [];
  if (variantLogic) lines.push(variantLogic, "");
  lines.push("  return (");
  const variantAttr = spec.variants.length > 1 ? ` variant={variant as any}` : "";
  const disabledAttr = disabledProp ? ` disabled={${disabledProp}}` : "";
  const styleAttr = tokenStyles ? ` style={${tokenStyles}}` : "";
  lines.push(`    <Button className={cn(className)}${variantAttr}${disabledAttr}${styleAttr} {...props}>`);
  if (iconProp) lines.push(`      {${iconProp} && <span className="mr-2">{${iconProp}}</span>}`);
  if (labelProp) lines.push(`      {${labelProp}}`);
  lines.push("    </Button>");
  lines.push("  )");
  return lines.join("\n");
}

function buildInputComponent(spec: ComponentSpec, tokenStyles?: string): string {
  const props = Object.keys(spec.props);
  const labelProp = props.find((p) => /label/i.test(p));
  const placeholderProp = props.find((p) => /placeholder|hint/i.test(p));
  const valueProp = props.find((p) => /value/i.test(p));
  const errorProp = props.find((p) => /error/i.test(p));

  const lines: string[] = [];
  lines.push("  return (");
  const styleAttr = tokenStyles ? ` style={${tokenStyles}}` : "";
  lines.push(`    <div className={cn("grid gap-2", className)}${styleAttr} {...props}>`);
  if (labelProp) lines.push(`      {${labelProp} && <Label>{${labelProp}}</Label>}`);
  lines.push(`      <Input${placeholderProp ? ` placeholder={${placeholderProp}}` : ""}${valueProp ? ` value={${valueProp}}` : ""} />`);
  if (errorProp) lines.push(`      {${errorProp} && <p className="text-sm text-destructive">{${errorProp}}</p>}`);
  lines.push("    </div>");
  lines.push("  )");
  return lines.join("\n");
}

function buildAvatarComponent(spec: ComponentSpec, tokenStyles?: string): string {
  const props = Object.keys(spec.props);
  const srcProp = props.find((p) => /src|avatar|image|url/i.test(p));
  const nameProp = props.find((p) => /name|alt/i.test(p));

  const lines: string[] = [];
  lines.push("  return (");
  const styleAttr = tokenStyles ? ` style={${tokenStyles}}` : "";
  lines.push(`    <Avatar className={cn(className)}${styleAttr} {...props}>`);
  if (srcProp) lines.push(`      <AvatarImage src={${srcProp}} alt={${nameProp ?? '""'}} />`);
  lines.push(`      <AvatarFallback>{${nameProp ? `${nameProp}?.slice(0, 2).toUpperCase()` : '"?"'}}</AvatarFallback>`);
  lines.push("    </Avatar>");
  lines.push("  )");
  return lines.join("\n");
}

function buildDialogComponent(spec: ComponentSpec, tokenStyles?: string): string {
  const props = Object.keys(spec.props);
  const titleProp = props.find((p) => /title/i.test(p));
  const descProp = props.find((p) => /desc|description/i.test(p));
  const triggerProp = props.find((p) => /trigger|label|button/i.test(p));
  const childrenProp = props.find((p) => /children|content|body/i.test(p));

  const lines: string[] = [];
  lines.push("  return (");
  const styleAttr = tokenStyles ? ` style={${tokenStyles}}` : "";
  lines.push(`    <Dialog>`);
  lines.push(`      <DialogTrigger asChild>`);
  lines.push(`        <Button variant="outline">{${triggerProp ?? '"Open"'}}</Button>`);
  lines.push(`      </DialogTrigger>`);
  lines.push(`      <DialogContent className={cn(className)}${styleAttr}>`);
  lines.push(`        <DialogHeader>`);
  if (titleProp) lines.push(`          <DialogTitle>{${titleProp}}</DialogTitle>`);
  if (descProp) lines.push(`          <DialogDescription>{${descProp}}</DialogDescription>`);
  lines.push(`        </DialogHeader>`);
  if (childrenProp) lines.push(`        {${childrenProp}}`);
  lines.push(`      </DialogContent>`);
  lines.push(`    </Dialog>`);
  lines.push("  )");
  return lines.join("\n");
}

function buildCardComponent(spec: ComponentSpec, hasBadge: boolean, tokenStyles?: string, variantLogic?: string | null): string {
  const props = Object.keys(spec.props);
  const titleProp = props.find((p) => p.toLowerCase().includes("title"));
  const valueProp = props.find((p) => p.toLowerCase().includes("value") || p.toLowerCase().includes("metric"));
  const descProp = props.find((p) => p.toLowerCase().includes("desc") || p.toLowerCase().includes("subtitle"));

  const lines: string[] = [];
  if (variantLogic) lines.push(variantLogic, "");
  lines.push("  return (");
  const styleAttr = tokenStyles ? ` style={${tokenStyles}}` : "";
  const variantClass = spec.variants.length > 1 ? ", variantClasses" : "";
  lines.push(`    <Card className={cn("${defaultClasses(spec)}"${variantClass}, className)}${styleAttr} {...props}>`);

  if (titleProp || descProp) {
    lines.push("      <CardHeader>");
    if (titleProp) {
      lines.push(`        <CardTitle>{${titleProp}}</CardTitle>`);
    }
    if (descProp) {
      lines.push(`        <CardDescription>{${descProp}}</CardDescription>`);
    }
    lines.push("      </CardHeader>");
  }

  lines.push("      <CardContent>");
  if (valueProp) {
    lines.push(`        <div className="text-2xl font-bold">{${valueProp}}</div>`);
  }

  // Render remaining props
  for (const name of props) {
    if (name === titleProp || name === valueProp || name === descProp) continue;
    if (hasBadge && (name.toLowerCase().includes("status") || name.toLowerCase().includes("tag"))) {
      lines.push(`        {${name} && <Badge>{${name}}</Badge>}`);
    } else {
      lines.push(`        {${name} && <span className="text-sm text-muted-foreground">{${name}}</span>}`);
    }
  }

  lines.push("      </CardContent>");
  lines.push("    </Card>");
  lines.push("  )");
  return lines.join("\n");
}

function defaultClasses(spec: ComponentSpec): string {
  const classes: string[] = [];

  if (spec.variants.length > 1) {
    classes.push("transition-all");
  }

  return classes.join(" ");
}

function mapPropType(type: string): string {
  const clean = type.replace("?", "").trim();

  const mapping: Record<string, string> = {
    string: "string",
    number: "number",
    boolean: "boolean",
    "string[]": "string[]",
    "number[]": "number[]",
    ReactNode: "React.ReactNode",
  };

  return mapping[clean] ?? clean;
}

/**
 * Build a CSS variable style object from design tokens that match the component.
 * Returns a JS object literal string for use in style={...}, or undefined if no tokens match.
 */
function buildTokenStyles(spec: ComponentSpec, tokens: DesignToken[]): string | undefined {
  if (tokens.length === 0) return undefined;

  const name = spec.name.toLowerCase();
  const styles: string[] = [];

  // Find tokens whose name contains this component's name
  for (const token of tokens) {
    const tokenName = token.name.toLowerCase().replace(/[\s/]/g, "-");
    if (tokenName.includes(name) || name.includes(tokenName.split("-").pop() ?? "")) {
      const value = Object.values(token.values)[0];
      if (value !== undefined) {
        // Use CSS variable reference so it responds to theme changes
        styles.push(`"${token.cssVariable.replace("--", "")}": "var(${token.cssVariable})"`);
      }
    }
  }

  // Also inject radius tokens if component uses Card
  if (spec.shadcnBase.includes("Card")) {
    const radiusToken = tokens.find((t) => t.type === "radius" && t.name.toLowerCase().includes("card"));
    if (radiusToken) {
      styles.push(`borderRadius: "var(${radiusToken.cssVariable})"`);
    }
  }

  if (styles.length === 0) return undefined;
  return `{ ${styles.join(", ")} }`;
}
